version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: task-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: task-backend
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/taskdb
      - JWT_SECRET=your_secret_key
      - NODE_ENV=production
      - CORS_ORIGIN=http://localhost:5173
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: task-frontend
    ports:
      - '5173:4173'
    depends_on:
      - backend

volumes:
  mongo_data:
